//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Collections.Generic;


namespace Rock.Client
{
    /// <summary>
    /// Recipient Result Information for the Statement Generator
    /// </summary>
    public partial class FinancialStatementGeneratorRecipientResultEntity
    {
        /// <summary />
        public decimal ContributionTotal { get; set; }

        /// <summary />
        public string Country { get; set; }

        /// <summary />
        public string FooterHtmlFragment { get; set; }

        /// <summary />
        public int GroupId { get; set; }

        /// <summary />
        public string Html { get; set; }

        /// <summary />
        public bool IsComplete { get; set; }

        /// <summary />
        public bool IsInternationalAddress { get; set; }

        /// <summary />
        public string LastName { get; set; }

        /// <summary />
        public Guid? LocationGuid { get; set; }

        /// <summary />
        public string NickName { get; set; }

        /// <summary />
        public bool OptedOut { get; set; }

        /// <summary />
        public int? PersonId { get; set; }

        /// <summary />
        public decimal? PledgeTotal { get; set; }

        /// <summary />
        public string PostalCode { get; set; }

        /// <summary />
        public int? RenderedPageCount { get; set; }

        /// <summary>
        /// Copies the base properties from a source FinancialStatementGeneratorRecipientResult object
        /// </summary>
        /// <param name="source">The source.</param>
        public void CopyPropertiesFrom( FinancialStatementGeneratorRecipientResult source )
        {
            this.ContributionTotal = source.ContributionTotal;
            this.Country = source.Country;
            this.FooterHtmlFragment = source.FooterHtmlFragment;
            this.GroupId = source.GroupId;
            this.Html = source.Html;
            this.IsComplete = source.IsComplete;
            this.IsInternationalAddress = source.IsInternationalAddress;
            this.LastName = source.LastName;
            this.LocationGuid = source.LocationGuid;
            this.NickName = source.NickName;
            this.OptedOut = source.OptedOut;
            this.PersonId = source.PersonId;
            this.PledgeTotal = source.PledgeTotal;
            this.PostalCode = source.PostalCode;
            this.RenderedPageCount = source.RenderedPageCount;

        }
    }

    /// <summary>
    /// Recipient Result Information for the Statement Generator
    /// </summary>
    public partial class FinancialStatementGeneratorRecipientResult : FinancialStatementGeneratorRecipientResultEntity
    {
    }
}
